### ISSUE TITLE
F15V5 Pixels flash to black if 1st universe is not being sent e131

### ISSUE THREAD

**Issue by barshow** [Pixelcontroller/f16v5_issues#10]
I have a show where sometimes I only run flood lights which are on a high universe number internally #62( e131 114) for my example.  And If I don't send universe #1(e131 50), all the pixels flash black for a frame at a seemingly random interval.  I measured the output with an oscilloscope and it is sending all 0 bits.  But as soon as I start sending data on universe #1 it works.  

The universe number's I'm reference are the # from the status page where # -> e131 universe.

If I send to universe #2 the problem still exists, so it seems there is something special about the first universe.  Maybe its synchronize sending?  

Another interesting tidbit is the status page, the packet count after universe # 55 does not reflect correctly to the universe that is actually receiving data.

<img width="1449" alt="Screenshot 2024-10-27 at 9 37 16 PM" src="https://github.com/user-attachments/assets/17e105ac-b1c7-4e84-8b34-038343c28ac9">

In that image I am sending e131 universe 50, and e131 universe 114.  The pixel output is correct, however the package count is incorrect.

Protocol priority and protocol synchronization are both off.

I am on build 32, this is also a problem on 30

**Comment by keithsw1111** [comment]
Email us at support@pixelcontroller.com I think I already have a fix for this.

**Comment by keithsw1111** [comment]
Closing this as i believe this is resolved.
