### ISSUE TITLE
Blown E fuse won't reset

### ISSUE THREAD

**Issue by Niceguy4186** [Pixelcontroller/f16v5_issues#11]
Hi, my port 8 has a blown E fuse that won't reset.  I disconnected the wire, rebooted, completely reset the controller, cycled power, updated firmware, checked make sure nothing is on the bottom.   Any thoughts?

**Comment by Niceguy4186** [comment]
Alright, think i found it, power injection was from wrong power supply.  I moved this port to an expansion port different controller, and it blew two efuses also on the original power source (port 1 and 2) (that have been working just fine.)    I just moved all ports with power injections to the same power supply (ports 9-16) and that seemed to fix it.  

But doesn't explain why it wouldn't reset even with nothing connected.  Or why the other ones ports with power injection didn't blow first.

**Comment by dpitts** [comment]
HI

Not sure. You can send it to us to look at.

12605 Black Hills Dr.
Falcon CO 80831


Thank you,

David Pitts
***@***.***

From: Niceguy4186 ***@***.***>
Sent: Sunday, December 1, 2024 7:00 AM
To: Pixelcontroller/f16v5_issues ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Pixelcontroller/f16v5_issues] Blown E fuse won't reset (Issue #11)


Hi, my port 8 has a blown E fuse that won't reset. I disconnected the wire, rebooted, completely reset the controller, cycled power, updated firmware, checked make sure nothing is on the bottom. Any thoughts?
