### ISSUE TITLE
Fuse status on SRx1 v5 unknown

### ISSUE THREAD

**Issue by HarryWeppner** [Pixelcontroller/f16v5_issues#16]
Hi,

We connected an SRx1 v5 to a F16 v5 controller (port 17-20). Its id setting is 0.

Ports 1 and 2 on the SRx1 v5 corresponding to 17 and 18 on the controller are connected and work, but the controller doesn't show the e-fuse status for any of the ports. In the web UI the port status remains black with status unknown.

I updated to the latest SRx1 v5 firmware, but am not sure how to verify that it applied.

How can the controller see and also manage the fuse status on a SRx1 v5 receiver?

Thanks, Harry.

**Comment by dpitts** [comment]
To receive fuse status the receiver needs to be in SmartReceiver mode (ID="A,B,C,D,E or F") The controller needs to be set also to match the board ID of receiver.

**Comment by HarryWeppner** [comment]
@dpitts , thanks! I changed the SRx1 id to A and reconfigured the outputs to be 17a through 20a and the fuse status works perfectly now.
