### ISSUE TITLE
F16v5 not sending FPP Ping packet at startup....

### ISSUE THREAD

**Issue by dkulp** [Pixelcontroller/f16v5_issues#2]
The F16v5 is properly responding to FPP Discovery Ping packets with it's own ping packet.   However, it should also send out that ping packet when it boots to "announce" itself.    Right now, if you change the F16v5 from one of the bridge modes to remote mode or vice versa, the FPP instances are not aware of the change and will continue to show the old mode on their multisync page.

**Comment by cybercop23** [comment]
Is it safe to assume same is happening for V3s and V4s?

**Comment by keithsw1111** [comment]
I dont remember which build this was added in but it is definitely in the latest builds. It sends one ping shortly after the network comes up on both wifi and wired connections.
