### ISSUE TITLE
32 Firmware update problem

### ISSUE THREAD

**Issue by gdackerm** [Pixelcontroller/f16v5_issues#3]
1 - download firmware file
2 - from the ethernet connected controller, update firmware, select file
3 - status bar immediately shows complete, however, takes several minutes and pop-up window stops.
4 - select Status page and web page is non responsive.
5 - internal display on controller is black, no response to physical buttons on board.

Power lights are on, network port green with flickering link status.  Cycle power and controller boots up and is accessible showing build 31 on status screen.

**Comment by keithsw1111** [comment]
Please confirm you actually downloaded the FL3. There are instructions there as many people get it wrong.

Also are you uploading to wifi or wired?

**Comment by keithsw1111** [comment]
Closed due to lack of a response. Please reopen if this is still a concern.
