### ISSUE TITLE
Differential receiver ports get hot

### ISSUE THREAD

**Issue by Anthony536** [Pixelcontroller/f16v5_issues#4]
I'm not using the ports.  They have no ethernet cable connected.  Data is not being sent to them.  However, they get what I'd consider hot, not even warm.  That's got to be a good chunk of energy wasted.

**Comment by keithsw1111** [comment]
This is normal behaviour. The differential sending chips have always run warm. On a F16 it is no big deal. On a F48 we allow for a fan for this reason. The chips dont know there is no data being sent. They are always sending what they see on the input ... even if it is just the line being held in a single state.

**Comment by Anthony536** [comment]
Thanks for the response.  Without them being connected, what's generating the heat?  It's definitely wasteful and seems like attention should be given to better efficiency.

**Comment by dpitts** [comment]
Hi

The controller has no detection for which receiver is connected. The V4 receivers do not give any feedback so there is no way to determine if they are connected. The differential IC’s are always on.

Thank you,

David Pitts
***@***.***
