### ISSUE TITLE
F16v5 on build 32 not toggeling fuses on input

### ISSUE THREAD

**Issue by stijn-dhondt** [Pixelcontroller/f16v5_issues#5]
Hi,

When i configure input 1 or 2 as a "set fuse" action with a value of 2 it won't toggle the fuses between on and of.

Regards,
Stijn

**Comment by keithsw1111** [comment]
Can you save and upload your settings file

**Comment by stijn-dhondt** [comment]
Hi @keithsw1111,

This is the current config.


[Falcon_F16V5_EE58.json](https://github.com/user-attachments/files/16992795/Falcon_F16V5_EE58.json)

**Comment by keithsw1111** [comment]
Do you have both sides of the board powered. When it does a fuse toggle it checks the status of port 1s fuse. If the left side of the board is unpowered then the toggle is undefined. I may change the code to check V1 and if V1 is < 5V I may instead probe port 9.

**Comment by keithsw1111** [comment]
If you desperately need the fix email us at suppport@pixelcontroller.com. Failing that it will be in the next build but I cant say when that will be.
