### ISSUE TITLE
F16 V5 Fuses Toggle ON

### ISSUE THREAD

**Issue by Strod35** [Pixelcontroller/f16v5_issues#6]
I have an F16V5 Build 32 Rev Controller connected with 1 each one SRX1 & 2 V5 bld 3 Rev receivers to port 17-20 SR chain RJ45 Port and 21-24 SR port. 

It runs test fine, and sequence run fine but when I shut off a sequence, all fuses toggle off as set due to no data. after about 15 seconds then the 1st 19 lights on the 1st prop of each SR come on and the first two fuse ports turn on.  I have tried other SRx2 V5 and SRx1 V5's with the same issue and different RJ45 outputs from the F16V5 and cables.  I should get an F-tester today to maybe help troubleshoot   

The switch on the SRX2 is set to A and the Srx1 on the other port is set to A as well.  I emailed Pixel controller but have not seen a response yet.  Attached is the image of the prop lights and the JSON.  All props show the same light numbers but the color of the last light may be a different color.

![image](https://github.com/user-attachments/assets/25a80c61-5b4e-4b78-bc1a-0bd4d67db26f)
[F16V5_01 (2).json](https://github.com/user-attachments/files/16993465/F16V5_01.2.json)

**Comment by keithsw1111** [comment]
The fact they come on suggests it saw data.

I am not sure we have enough information here to determine why.

The cat-5 cable from controller to SR ... is it a direct cable or does it go through some sort of connection/extension in/out of the box.

Does this happen when you turn on/off test on the controller ... or is it when receiving data from from something like xLights/FPP?

**Comment by keithsw1111** [comment]
Did you email support@pixelcontroller.com ... I have not seen an email like this there?

**Comment by Strod35** [comment]
Keith,

Yes see below.  It went to Daud and not Support.  I used the support option on the PixelController web site.

 

From: tstrodtbeck35 ***@***.*** ***@***.***> >
Date: September 9, 2024 at 7:11:21 PM MDT
To: ***@***.*** ***@***.***> 
Subject: F16V5. & SRx2 V5 issues

﻿David,

 

I know it is a busy time for you all.  

 

I have an F16V5 Build 32 Rev connected with one SRX2V5 bld 3 Rev connected to port 17-20 A/B.   SR chain RJ45 Port.  It runs test fine, and sequence runs fine but when I shut off a sequence.... the Auto fuses come as set due to no data and the 1st 19 lights with one a different collar on the SRX2 port 17A light UP.  This same thing happens on an SRX1 V5 Smart receiver and other ports.

 



 

I noticed tonight that in the FPP visualizer it sees the SRx and correct build.  Then it reverts to a normal status and does not report temps or build rev.  Also pixel count doesn’t work on the SRx or ever the F16V5.   Also if I ask it to count the pixels I get a time out and have to reboot the F16.

 

Now I am thinking my problem is the F16V5 and not the SRx.    Any ideas what to check. 

 

Best regards,

Tim

 

 

My Best Regards,

Tim Strodtbeck

**Comment by keithsw1111** [comment]
I will take a look at this during the week.

**Comment by Strod35** [comment]
Kieth and David,

 

Here is a little more detail.

 

*	I have the F16V5 Connected (192.168.100.5) to a Show Player (192-168.100.2) over a dedicated Show network in Bridge Mode.
*	The F16V5 is set up in DDP Mode to the Show Player and Communicates fine with the Player. 
*	The SRx2 is connected to the first RJ45 port dial set to “A” (Chanels 17-20 A&B) of the Receiver section on the F16V5
*	I also connected and SRx1 set to the 3rd RJ45 Port (Channel 21-24A) of the F16V5 and set the SRx1 to “A” on the dial. 
*	No other receivers are connected. 
*	I only installed PROPS on Ports 1& 2 of the F16 and both SRx’s

 

1.	If I run test or a sequence on the F16V5 all lights operate as fine.  When data stops and after the 15 seconds the fuses Open up as normal.  
2.	Then after about 10 seconds later the 1st Prop on each of the SRx’s show this 19 lights lit and all the fuses close allowing data.  The F16 doesn’t turn on the lights it leaves the fuses open.  Below is my Fuse times.
3.	I change Network cables and also moved ports with the same results on the SRx’s.  I did notice the time below is not correct and I cannot get the NTP server as I am on the internet with the Eth0.  Each time I boot up the F16 I have to set the time manually.  I don’t have a battery in there.  I need to find out what batter to purchase.
4.	I did notice that when this condition is there the data lines on the SRx’s are flashing the first LED.

 

I have an F-Test box but need to get familiar with it to check these out with it and see if it shows anything.





 

My Best Regards,

Tim Strodtbeck

**Comment by Strod35** [comment]
Keith,

 

I did find something else today.  When I go into the visualizer right after I power up I get this on the SRx’s. Normal right indication of the SRx2 and the build.  The pixel counts are not correct but I run EVO’s in my show and it does not count them right anywhere.

 



 

After the ending as noted in previous post and the 19 lights on first prop come on, this all seems to lock up the F16V5 Communications.  I have to power down the F16V5 and SRx’s to get it back communications. Then it will show the proper version of SRx until the fuses to the image beow.  So it seems to loose communications with the SRx’s.  I also noted if I try to reboot and do a pixel count in the F16V5 Visualizer this will lock up communications also.

 

When it is in the below state I can go back to my show player and start a new sequence and the SRx’s with show the fuse status ok until no data is received and then it looses status. 



 

 

 

 



My Best Regards,

Tim Strodtbeck

**Comment by keithsw1111** [comment]
EVOs are a problem … they don’t have a differentiated current draw when they are on vs off which makes them impossible to count with any accuracy.

**Comment by keithsw1111** [comment]
So looking at this ... there are 2 things going on here.

There are the local ports which turn off their fuses after the time set on the settings page. It sounds like this is working fine.

Then there are the SRs. They work a little differently as we did not want them reliant on the controller to turn their fuses on and off (doing so creates other potential scenarios where they wont come back on). In the case of the SRs.

- The data to the SR should stop sending. This will be evident by the 4 data LEDs turning off.
- About a minute or so later the SR should turn off the fuses on the SR and then wait to see data again from the controller.
- When that data arrives all fuses should be turned back on.

When i tested it just now this is the behaviour I see. I tested it both with the controller test button and by sending it DDP data.

Having or not having pixels plugged in should not change this behaviour in any way.

Can you tell me where you see the deviation from this behaviour.

**Comment by Strod35** [comment]
I am struggling to reproduce this. The only time I am unable to do this is if I am using a hidden advanced option to treat all receivers as V4 receivers (an option I doubt you even have as it was only built in the past week and you have no reason to be using it even if you had it).

That said the receivers turning off is not dependent on you manually turning them off

If you set these options:

***@***.***

In particular the checkbox on the settings page then about a minute after the show stops running all the receivers fuses will automatically turn off as the receiver has stopped receiving data. As soon as they see data again they will automatically turn back on and play your pixels.

Keith

From: ***@***.*** ***@***.***>
Sent: Monday, 16 September 2024 11:13 PM
To: 'Pixelcontroller/f16v5_issues' ***@***.***>; 'Pixelcontroller/f16v5_issues' ***@***.***>
Cc: 'Author' ***@***.***>; PixelController Support ***@***.***>; David Pitts ***@***.***>
Subject: RE: [Pixelcontroller/f16v5_issues] F16 V5 Fuses Toggle ON (Issue #6)

Keith,

Yes I understand.  Counting is not a big issue as I am pretty good at counting them.  The main thing I want to solve is being able to kill power when the show is over.   I can power the whole show down but that is not why I purchased the F16v5.  Today I turned the fuses off from the status screen and it does not turn off the SRx’s.  I was hoping if turning ALL fuses off worked I could just make a command somehow to turn them off at the end of the show but they stay on. I also checked into the ZOOM room and the team there went through all my settings and said they look correct.  I will try to put an F8 Distro Board in the SRx box and wire into the SRx to see if that changes things.

***@***.***

My Best Regards,
Tim Strodtbeck

**Comment by Strod35** [comment]
Keith,

 

Here is when my box was powered up and idle. I have 400 EVO’s on Port 1&2 of an SRx2 and 1 port on an SRx1.  Also below is a step by step.  I have a 1:30 sec video I took showing this but not sure how to upload it to you.  The server will not allow. 

 

*	Show idle and no data going to Prop on SRx2



*	Show Sequence running.  – Looks ok



 

 

Time Stamps to Video – Video of SRx2 – SRx1 operates the same.

*	Power On state after 5 min
*	00:00    Power onto SRx1 & SRx2 – No data

*	Data Light 1 On blinking – All others off
*	Fuse Lights – Off

 

*	00:08    Start Alternating Test on F16V5 – OK

*	Data Lights 1-4 On
*	Fuse lights – Off

 

*	00:22    Stop Test on V5 – All ok

*	00:32    After 10 seconds Data line 1 is on All others off
*	00:34    Then Data line 1 is off.
*	 

*	00:47    Fuse 3-8 open but Fuse 1-2 stay off.

*	6 Lights come on on SRx1 and SRx2 props – Nodes 1-6 ON 

*	00:54    All lights off on props all fuses Open or lights on

*	 

*	1:22       19 Lights on the SRx1 prop, Nodes 1-19,  #19 is red and others white – Sorry I mentioned this one, I had both running and the SRx1 seemed to be about 5 seconds ahead of the SRx2.

 

*	1:28       19 lights on the SRx2 prop, Nodes 1-19,  #19 is red and others white

*	Data line flashes and fuses are closed.

*	End        Normal standby is like the Video shows 

*	Data Light 1 On blinking – All others off
*	Fuse Lights – Off

 

 

My Best Regards,

Tim Strodtbeck

**Comment by Strod35** [comment]
Keith,

 

Here is a link.  2024_09 SRx Issue (youtube.com) <https://www.youtube.com/watch?v=SRdVSidEnEs&t=3s> 

 

My Best Regards,

Tim Strodtbeck

**Comment by keithsw1111** [comment]
In your video ~ 1:19 I can see all the fuses are off ... but your voice over says that the lights have just come on. Unless the video is not showing it correctly I dont see how that can be the case. The fuses are off so they should have no power.

Is all the power to these pixels coming through the SRx2? You are not doing power injection?

Does this only happen on the SRx2 ... not on a SRx1?

**Comment by Strod35** [comment]
Keith,

 

I have the following with No power injection in my show at this time.  This happens only on the SRx receivers and on each of the channels from the F16V5.  I have moved them around and I tried only one receiver to the F16.  I have tried only SRx2 and only SRx1.  I have 2 SRx2’s and three SRx1’s and this is the same on all of them.   

 

I am going to go back a revision on the F16 and the SRx’s and see what happens.  I did not see this in the spring and I just upgraded the F16 and SRx’s to the latest builds.  I am not Chaining off any of the SRx’s but I may move an SRx1 to my first SRx2 Channel C and see what happens there.  Unfortunately I don’t have another F16V5 to try.  I will purchase one this winter. 

 

At the 1:19 mark my SRx1 the lights came on the Prop.  Sorry I did not film that SRx1 prop.  I mistakenly mentioned lights on.  Ignore my comment on at the 1:19 mark and refer to the 1:28 where the SRx2 lights came on the prop.  

 

Time Stamps to Video – Video of SRx2 – SRx1 operates the same.

*	Power On state after 5 min
*	00:00    Power onto SRx1 & SRx2 – No data

*	Data Light 1 On blinking – All others off
*	Fuse Lights – Off

 

*	00:08    Start Alternating Test on F16V5 – OK

*	Data Lights 1-4 On
*	Fuse lights – Off

 

*	00:22    Stop Test on V5 – All ok

*	00:32    After 10 seconds Data line 1 is on All others off
*	00:34    Then Data line 1 is off.

 

*	00:47    Fuse 3-8 open but Fuse 1-2 stay off.

*	6 Lights come on on SRx1 and SRx2 props – Nodes 1-6 ON 

 

*	00:54    All lights off on props all fuses Open or lights on

 

*	1:22       19 Lights on the SRx1 prop, Nodes 1-19,  #19 is red and others white – Sorry I mentioned this one, I had both running and the SRx1 seemed to be about 5 seconds ahead of the SRx2.

Ignore this comment in the video as I was looking at my SRx1 Prop, not being filmed and misspoke.

 

*	1:28       19 lights on the SRx2 prop, Nodes 1-19,  #19 is red and others white

*	Data line flashes and fuses are closed.

 

*	End        Normal standby is like the Video shows 

*	Data Light 1 On blinking – All others off
*	Fuse Lights – Off

 

 

My set-up

F16V5 --> SRx2 Channel 17-20 A&B - 17A Lights 19 lights 

F16V5 --> SRx1 Channel 21-24 A - 21A Lights 19 lights 

F16V5 --> SRx2 Channel 17-20 A&B - 25A Lights 19 lights 

 

 



 

 

 

My Best Regards,

Tim Strodtbeck

**Comment by Strod35** [comment]
Keith,

 

I am putting together a whole summary PPT file with pictures.  I was able to prove everything is fine with Firmware 28, 30, 31.  But when I go to Build 32 it is bad. I will send later today.  See the attached Config file.

 

My Best Regards,

Tim Strodtbeck

**Comment by Strod35** [comment]
Keith,

 

See the attached PPT summary.

 

Also Comments below in Blue.

 

My Best Regards,

Tim Strodtbeck

**Comment by keithsw1111** [comment]
Can you email me the ppt ... sending attachments via email to github does not work.

**Comment by keithsw1111** [comment]
CFG file also did not get to me.

**Comment by keithsw1111** [comment]
Fixed with interim build sent to user.
