### ISSUE TITLE
Auto reset efuse enhancement

### ISSUE THREAD

**Issue by reelpilot** [Pixelcontroller/f16v5_issues#7]
In 2023 I had an intermittent issue where some ports would have the efuse trip offline. The issue appeared on about 30% of nights and was isolated to about 8 total ports out of 48 in use across multiple controllers / remote receivers. The occurrence of the tripping was not correlated to weather and only occurred on ports with roughly 175 or greater pixels with the most of the impacted strings being about 240 pixels. The brightness was set to 30%, but later changed to 10% without any noticeable change in the rate of tripping. The same series of sequences was played each night, so on most nights there were no issues, but on the 30% of nights that did have issues with tripping, sometimes it would only happen once and other times it would happen 2-3 times. 

The impacted ports when set to white and the initial 30% brightness would indicate an amp draw well under the 5 amp threshold, however during realtime conditions during the show it was not unusual to notice a momentary fraction of a second spike greater than 6 amps. I suspect that this momentary spike is what caused the tripping as I could manually reset the port right after it tripped and it would run normally for a period of time if not the rest of the night. 

The addition of an advanced setting that would enable the user to enable the automatic reset of a tripped efuse would be a huge benefit as I'm not outside watching the show the entire night and often did not notice that sections of the display were offline until I checked the status page of the controller. Perhaps something along the line of x number of resets are allowed within x period of time would enable the safe resetting of an efuse from a momentary high amperage spike. If the tripping kept occurring outside of this parameter then the efuse would not automatically reset as it might indicate an actual fault.

**Comment by keithsw1111** [comment]
I have sent you a test build that may help here. It will test 5 times in 5 MS ... resetting each time before accepting that a fuse is truly blown. The SRx boards already do this.
