### ISSUE TITLE
F16v5 Renard does not work

### ISSUE THREAD

**Issue by cf-mp** [Pixelcontroller/f16v5_issues#9]
Hi, We upgraded one of our F16v3s last season to a F16v5 and the serial port off of the controller does not work for correctly with Renard protocol.  I did not get a chance to test if they worked on DMX as I would need to reflash all of the PICs on the renard controllers.  Please let me know if this is something you can fix before I break out the PIC flasher.  Thanks!

**Comment by keithsw1111** [comment]
Can you email us at support at pixelcontroller.com ... I have a test build for you that may fix this problem.

**Comment by keithsw1111** [comment]
Test build sent to user. Will include in build 33 if it works as expected.
